Aram-Anderson/bike-share

- app/controllers/bike_share_app.rb
- app/views/stations.erb
@blsrofe @Aram-Anderson @JoelLindow 
Created a stations.erb and an all.erb. 
stations.erb displays a dashboard where you can select how you want to display the stations. 
all.erb displays all of the stations in a list. 
Should we have a folder for all of the stations view? or should we append these views with "station"?
Added routes in bike_share_app.rb
> create stations dashboard

- app/views/layout.erb
Just adds layout.erb page with code to provide static navbar and footer to each page viewed in client window.
> add navbar and footer in layout.erb page

- .rspec
- Gemfile
- app/controllers/bike_share_app.rb
- app/views/stations/show.erb
- spec/features/user_can_view_stations_show_spec.rb
- tmp/capybara/capybara-201708191921219825346432.html
- tmp/capybara/capybara-201708191932136065568533.html
-Rspec Test Written and passing
- View works with testing and with actual seeded database.
> test and page working for show

- spec/models/stations_spec.rb
test made. Waiting on date format and then we will add validations to model to pass test
> Model Test Stations

- Gemfile
- app/controllers/bike_share_app.rb
- app/views/trips/index.erb
Paginate works for trips index. It's cool, and I like it.
> Paginate working on trips

- Gemfile
- db/seeds.rb
rake db:reset working right. There was a typo in the seeds file
> Fix typo in seeds.rb

- app/controllers/bike_share_app.rb
> controller was broken. added missing end tags

- app/controllers/bike_share_app.rb
Fixed broken new routes for trips and stations
> fixed both new routes for trips and stations

- app/views/stations/index.erb
- spec/features/user_can_view_all_stations_index_spec.rb
> Test view index

- app/models/station.rb
- app/views/trips_dashboard.erb
- spec/models/stations_spec.rb
Moves logic from station_dashboard to model
tests written for model
validations added to model and validation tests updated with quotes
all class method and validation tests now passing
> Move logic into model

- app/controllers/bike_share_app.rb
- app/views/stations/show.erb
- app/views/trips/dashboard.erb
- app/views/trips/edit.erb
- app/views/trips/index.erb
- app/views/trips/show.erb
- spec/features/trips_dashboard_spec.rb
Fixed trips/dashboard_spec. Tests passing.
> Trips dashboard spec

- app/controllers/bike_share_app.rb
- spec/features/trips_dashboard_spec.rb
Update route for 'trips-dashboard' to match spec
> Trip dashboard passing

- app/controllers/bike_share_app.rb
> Fix broken route

- app/controllers/bike_share_app.rb
- spec/features/user_can_view_all_stations_index_spec.rb
By changing station_4 installation date to a valid date, the test was able to actually create station_4. Title spec is passing now.
> fix user_can_view_all_stations_spec.rb 

- app/controllers/bike_share_app.rb
- app/models/trip.rb
- app/views/root/index.erb
- app/views/trips/dashboard.erb
- app/views/trips/edit.erb
- app/views/trips/index.erb
- app/views/trips/new.erb
- app/views/trips/show.erb
- spec/features/station_dashboard_spec.rb
- spec/features/trips_dashboard_spec.rb
- spec/features/user_can_view_trips_index_spec.rb
- spec/models/trip_spec.rb
Added trip validations, and fixed routes in stations-dashboard spec. All tests passing. CRUD working for trips.
> Trips validations

- app/controllers/bike_share_app.rb
- app/views/layout.erb
- app/views/trips/new.erb
- spec/features/user_can_create_a_new_trip_spec.rb
- spec/features/user_can_edit_a_trip_spec.rb
Spec created for trip/new and trip/:id/edit. All tests passing.
> Trips spec done

- app/views/trips/index.erb
- spec/features/user_can_view_trips_index_spec.rb
-Fixed error in test
-Added some magical table styling to the trips/index.erb view
-Edited verbage in index test to match edit button
> fixed tests. added table elements to trips index view

- app/models/trip.rb
- app/views/stations/dashboard.erb
- app/views/trips/dashboard.erb
For some reason this did not get changed in the dashboards last time.
> Finish moving logic

- app/public/css/custom.css
- app/views/stations/edit.erb
- app/views/stations/new.erb
- app/views/stations/show.erb
Aram. Merge my face off, bruuuuuuuh!
> crud views for station basic styled

- app/public/css/custom.css
- app/views/stations/edit.erb
- app/views/stations/show.erb
- app/views/trips/edit.erb
- app/views/trips/show.erb
A few views with basic styling plugged in
placeholders for maps on trips as well.
more to come. 
please merge
> much styling plugged in. Few more to go. See code

- app/views/trips/edit.erb
- app/views/trips/new.erb
- app/views/trips/show.erb
Nothing magical. Merge please.
> Just more styling for trips edit and new

- app/controllers/bike_share_app.rb
- app/models/station.rb
- app/views/stations/index.erb
Finally got the index for station to work. I had been missing the part about adding info to the stations route. Once I had that part in it was a matter of getting the styling right.
Thanks for letting me tackle this styling, even though I took so long on it!
> Index style

- spec/models/condition_spec.rb
model test for conditions added
x added to skip test until we plug in validations
> model test - conditions

- app/models/condition.rb
- spec/models/condition_spec.rb
- validations added.
- x removed from test
- test passing
> test un-xed. validations added. test passes.

- app/views/stations/show.erb
- app/views/trips/show.erb
Add green create new button to station show page, changed the trips show page to accommodate the normalization of the trips database.
> Show create new

- app/controllers/bike_share_app.rb
added all of the cruds for condition, changed a put into post for the trips routes
> Conditions crud

- app/models/condition.rb
- app/views/trips/dashboard.erb
- app/views/trips/index.erb
- app/views/trips/new.erb
- app/views/trips/show.erb
- spec/features/trips/trips_dashboard_spec.rb
All trips dashboard tests are passing now. Changed a piece of the dashboard view, where it was "an starting station" and changed it to "a starting station". 
Cause grammar yo
> Trips tests

- app/controllers/bike_share_app.rb
- app/views/trips/index.erb
Added a route to the controller for posting conditions
> add post route to controller

- app/models/condition.rb
added guard to condition model, so that it knows not to pull any nils into the database.
> New branch
